name: test-dispatch

on:
  workflow_dispatch:
    inputs:
      repo:
        description: Specify the repo
        type: string
        required: true

jobs:
  return-repo:
    runs-on: self-hosted
    steps:
      - env:
          REPO: ${{ inputs.repo }}
        run: echo $REPO
        name: echo repo

