# This workflow calls the master UI workflow with custom variables
# It will test all Epinio parts
name: STD-UI-Latest-Chrome

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 4 * * *'

# I do not know if I can refactor with a matrix in a reusable workflow?
jobs:
  commandCall-tests:
    uses: ./.github/workflows/master_std_ui.yml
    with:
      browser: chrome
      cypress_docker: cypress/included:10.11.0
      cypress_spec: cypress/e2e/unit_tests/commandCall-example.spec.ts
    secrets: inherit